### PR TITLE
Consolidate EC curve OIDs

### PR DESCRIPTION
**Pull request by edewata**
The EC curve OID constants in `PK11KeyPairGenerator` have been consolidated into `ECOIDs`.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Review by ckelleyRH — APPROVED** [review]
LGTM!

**Review by ckelleyRH — APPROVED** [review]
LGTM!

**Comment by edewata** [comment]
@fmarco76 @ckelleyRH Thanks!

**Pull request merged**
