### PR TITLE
Deprecated bsd source and svid source warnings

### PR DESCRIPTION
**Pull request by emaldona**
This one line change gets rid of all those warnings.

### CODE REVIEW

**Comment by cipherboy** [comment]
@emaldona Can I get you to split up these PRs a little more? It seems like there is a common patch set of:
 - 6a96e31
 - 804115e
 - fa5a7fe
 - 1a411b1
 - ea54c6f

in this PR, in #22, #24, #25, and #26.

I'm not sure if the last commit (ea54c6f) depends on 804115e, fa5a7fe, or 1a411b1. If it doesn't, then I'd maybe propose making a PR with 6a96e31 and ea54c6f, a separate PR with 804115e, and a perhaps a third with fa5a7fe and 1a411b1 (though those are more loosely related). I think that'd make it much more reviewable assuming there aren't many dependencies between those commits.

If you do that, that makes all of those PRs smaller and more reviewable on their own. If not, may I do so? You'll have to rebase afterwards.

(Doing so would also remove the merge commits which would be a nice bonus).

Thanks!

**Comment by emaldona** [comment]
I don't quite understand the comments. As I click in the various links I see one that was committed already and others that are not part of the recent pull requests. Let me quote from an email i sent to @edewata and see if this helps clarify

Completed the pull requests based on cherry picks from my fork as @edewata suggested
with 4 tiny cherries and one larger one:

https://github.com/dogtagpki/jss/pull/21
https://github.com/dogtagpki/jss/pull/22
https://github.com/dogtagpki/jss/pull/24
https://github.com/dogtagpki/jss/pull/25
https://github.com/dogtagpki/jss/pull/26
The first four can done in any order whereas 26 being much larger is best to review it last.
The 4 tiny ones could be merged into one if you folks think it makes the review easier. As @cipherboy pointed out the master branch in the emaldona fork id a bit out of sync with master in dogtagpki which I discovered while doing the pull request. I can merge and would have to update the pull requests. These pull requests refrain from doing anything related to OpenJDK 11 at all.  

Any OpenJDK-11 work should be postponed until later. OpenJDK-11 is due to be realeased on Sept 25 and Fedora will pick that up later and only as a technology preview.  What I have shown related to 11 is for informational purpose only so we can better understand the issues. Once f29 if out we can start finding the proper way to deal with those problems in preparation for f30.  I hope this helps clarify things a bit.

**Comment by cipherboy** [comment]
Apologies, perhaps I'm nitpicking a little, but I think some of these are valid points... :)

--- 

So... When I click on the commit tab of this PR and the others, I see [11 commits](https://github.com/dogtagpki/jss/pull/21/commits). If I were to merge this PR as-is, there'd be 11 new commits in upstream master, which I don't really want for the reasons outlined below (I want one). 

Responding to your point about committed already and not part of recent pull requests, well, they're on this PR so they are part of a PR... :)

In particular:

- The commit in this PR https://github.com/dogtagpki/jss/pull/21/commits/6a96e31ce4c87df5c8a95fbb3ebd5d3c0d82c37a is the same as the commit bef0b54d1477c6ce89d22d94ed67b4ba4d3431f4 in upstream master.
   - So please drop that commit from this PR and the others via rebasing against master.
- https://github.com/dogtagpki/jss/pull/21/commits/590c39e25981211f6300c6ec5dbc96ac641dc931 (PR) is a merge commit and shouldn't be merged and isn't necessary.
    - Please drop this commit as well. It should happen automatically when you rebase.
- https://github.com/dogtagpki/jss/pull/21/commits/a19f9cce0eef14528b6509d32af6016936b09598 -- Same as https://github.com/dogtagpki/jss/pull/21/commits/590c39e25981211f6300c6ec5dbc96ac641dc931 above
- The commit in this PR https://github.com/dogtagpki/jss/pull/21/commits/804115eb722f08eb4002ef08cb5b96c6bd312576
    - Doesn't appear to be in master (by searching log messages), ...
    - But perhaps would be a good patch to have...
    - And [exists](https://github.com/dogtagpki/jss/pull/22/commits) in PR #22 as the same commit hash (https://github.com/dogtagpki/jss/pull/22/commits/804115eb722f08eb4002ef08cb5b96c6bd312576) 
    - And exists in #24, #25 as well, again with the same hash.
    - But perhaps it belongs as part of #26 so I'm not sure why it is in these other four PRs (#21, #22, #24, and #25).
    - If you don't want it to be part of #26 because you don't think it fits the scope, (perhaps #26 should be "add deprecation annotations" versus "complete") or because #21, #22, #24, or #25 depend on its functionality (I don't _think_ they do but I've not looked at them closely enough to tell), then I'd recommend splitting it out into a separate PR and we'll merge that one (and mark these as WIP to show the dependency). 
    - In either case, this commit should exist and be merged in _one_ PR, not _five_, so I'd drop it from all but the one where it fits best. :)
- Same thing with commit https://github.com/dogtagpki/jss/pull/21/commits/fa5a7fe3c8f560df980c1d6e104620f67bc929c5 in this PR as with https://github.com/dogtagpki/jss/pull/21/commits/804115eb722f08eb4002ef08cb5b96c6bd312576.
    - It exists in #22, #24, #25, and #26 always with the same commit hash.
    - I'd rebase and drop it from most of the PRs and propose it as a separate PR as it'd be more easily reviewable. If these PRs do depend on it, mark them as WIP until it merges, at which point, you can rebase them and they'll include this patch.
- Same thing with this commit: https://github.com/dogtagpki/jss/pull/21/commits/1a411b16c646bf1059bb9ecc43d432749c3e834c in this PR as with https://github.com/dogtagpki/jss/pull/21/commits/804115eb722f08eb4002ef08cb5b96c6bd312576
    - Separate PR please or stick it with another related commit.
- Same thing with this commit: https://github.com/dogtagpki/jss/pull/21/commits/ea54c6f8cabc75e37e17d4ce7812ec9fb16a83ec in this PR as with https://github.com/dogtagpki/jss/pull/21/commits/804115eb722f08eb4002ef08cb5b96c6bd312576.
- This commit in the PR https://github.com/dogtagpki/jss/pull/21/commits/ea354b3b0c3ed44ca33f54ad5ca24df057d2ab18
    - I think is a merge commit but it looks messy?
    - If it is a merge commit and doesn't contain anything new, rebase and drop it please. :)
- This commit in the PR https://github.com/dogtagpki/jss/pull/21/commits/4f6939c357ba3b264d07a6c28a50ece52cff2d00
    - Is a merge commit, so please rebase and drop it.
- This commit in the PR https://github.com/dogtagpki/jss/pull/21/commits/8bfb6ddd83933f0a75015b2679b92f7857c2ee60
    - Is also a merge commit, so please rebase and drop it.


Which leaves the final commit:
 - https://github.com/dogtagpki/jss/pull/21/commits/a1a1a8cafaaee33246bce77ef7785daaa883c86b -- which should probably be the only commit this PR merges. :)

---

Total, according to GitHub, your PR has the following stats: +10 −6
But it is really hard to review because it is 11 commits that contradict each other. I think your real change is one line: https://github.com/dogtagpki/jss/pull/21/commits/a1a1a8cafaaee33246bce77ef7785daaa883c86b but it is really hard to tell that by looking at the commits.

What I'd perhaps do is create a new branch off of latest master (62c5f2027839fbe881228abe1675ebd9f0a942a6 as of the time of this writing) and cherrypick a1a1a8cafaaee33246bce77ef7785daaa883c86b in as the only commit, close this PR, and open a new one. I think it'd be the least amount of work for both of us. :)

Same thing holds for the other PRs.

---

Sorry about the long winded response, hopefully that's more clear now. :) To be clear, I think the issue stems from not having an up to date branch and merging into your branch rather than updating master and rebasing on top of it. You can either rebase your PR branches and drop the unnecessary commits (and perhaps copy them into other branches for separate PRs), or create a new branch and new PRs with a better scope. 


Thanks for the changes! :)

**Comment by emaldona** [comment]
Thank you, that long winded response makes things clearer. Rebasing the PR branches and dropping unnecessary commits seems prone to errors so I'll try the nee branch approach. I'm still a novice with GitHub so I'll be online as I try it in case I get stuck and need some help.

**Comment by cipherboy** [comment]
@emaldona Sure! I lurk in `#dogtag-pki` on Freenode so feel free to ask there and I can help. Sorry I didn't see your message last night, I had left work and hadn't yet gotten Internet set up at home.

**Comment by cipherboy** [comment]
I have:
 - Built this locally
 - Built master locally
 - Verified that the compile command is changed.
 - Verified that the warnings go away.
   - Before:
```
gcc -o Linux4.18_x86_64_glibc_PTH_64_DBG.OBJ/nsinstall.o -c -g -D_POSIX_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE -fPIC -DLINUX2_1  -Wall -Werror-implicit-function-declaration -Wno-switch -pipe -DLINUX -Dlinux -DHAVE_STRERROR -DXP_UNIX -DDEBUG -UNDEBUG -DDEBUG_cipherboy -D_REENTRANT -DUSE_UTIL_DIRECTLY -I../../../dist/Linux4.18_x86_64_glibc_PTH_64_DBG.OBJ/include -I../../../dist/public/coreconf -I../../../dist/private/coreconf  nsinstall.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from nsinstall.c:8:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
<next command>
```
   - After:
```
gcc -o Linux4.18_x86_64_glibc_PTH_64_DBG.OBJ/nsinstall.o -c -g -D_POSIX_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE -fPIC -DLINUX2_1  -Wall -Werror-implicit-function-declaration -Wno-switch -pipe -DLINUX -Dlinux -DHAVE_STRERROR -DXP_UNIX -DDEBUG -UNDEBUG -DDEBUG_cipherboy -D_REENTRANT -DUSE_UTIL_DIRECTLY -I../../../dist/Linux4.18_x86_64_glibc_PTH_64_DBG.OBJ/include -I../../../dist/public/coreconf -I../../../dist/private/coreconf  nsinstall.c
<next command>
```
 - That the tests pass on both branches.


Thanks for the patch, @emaldona! 

ACK

**Pull request merged**
