### PR TITLE
Only provision OAEP parameters when non-NULL

### PR DESCRIPTION
**Pull request by cipherboy**
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`

### CODE REVIEW

**Comment by cipherboy** [comment]
@jmagne Do you remember why I filed this?

**Comment by fmarco76** [comment]
Is there a case for OAEP without parameters requiring this change? If it is then the implementation looks OK to me and we could rebase and merge.

**Comment by fmarco76** [comment]
@cipherboy I am not sure there are implicit OAEP parameters but in any case the PR looks safe and should not provide any problem to the current supported cases and be safer for the other. Do you remember why this has not been merged?

**Comment by cipherboy** [comment]
@fmarco76 Honestly, no clue.

Maybe this was reported by covscan or similar?

**Comment by fmarco76** [comment]
@cipherboy OK. I think we can go ahead with this . Could you rebase to solve the conflicts?

**Review by jmagne — COMMENTED** [review]
This looks totally fine and non destructive. It can't hurt even if it is not needed for some reason.

**Comment by cipherboy** [comment]
@fmarco76 Updated

**Comment by fmarco76** [comment]
@cipherboy Thanks!

**Pull request merged**
