### PR TITLE
Fix shellcheck issues in build.sh and tomcat-start-wait.sh

### PR DESCRIPTION
**Pull request by ckelleyRH**
Set severity to only trigger failure on warnings or higher.

### CODE REVIEW

**Review by fmarco76 — APPROVED** [review]
LGTM

**Comment by ckelleyRH** [comment]
Thanks @fmarco76 !

**Comment by edewata** [comment]
Hmm.. looks like the changes broke Tomcat tests:
https://github.com/dogtagpki/jss/actions/workflows/tomcat-tests.yml
Could you take a look? Thanks!

**Comment by ckelleyRH** [comment]
> Hmm.. looks like the changes broke Tomcat tests: https://github.com/dogtagpki/jss/actions/workflows/tomcat-tests.yml Could you take a look? Thanks!

Oops, yeah I'll take a look!

**Pull request merged**
