### PR TITLE
Fix jss internal deprecation warnings #35

### PR DESCRIPTION
**Pull request by emaldona**

### CODE REVIEW

**Comment by emaldona** [comment]
My bad, truck load of copy-and-paste errors that I missed testing. Fixes coming.

**Comment by cipherboy** [comment]
@edewata Sorry, I misremembered who had written the [code this mirrors](https://github.com/dogtagpki/jss/blame/master/org/mozilla/jss/provider/javax/crypto/JSSCipherSpi.java#L263-L271).

@emaldona I'll review this week hopefully.

**Comment by cipherboy** [comment]
@emaldona Any chance I could get you to rebase this properly? I think I finally have time to review this. :)

**Comment by cipherboy** [comment]
@emaldona I've rebased this for you.

**Comment by cipherboy** [comment]
ACK this is fine. At some point we can go through and remove most of the class references (the original code had it so I'd consider fixing it up out of the scope of this) and replace it with `instanceof` instead.

**Pull request merged**
