### PR TITLE
Update .gitignore for JSS 4.8

### PR DESCRIPTION
**Pull request by edewata**
I also backported some changes from the main branch to fix the CI.

### CODE REVIEW

**Comment by ckelleyRH** [comment]
There looks to be a lot of maven-built binaries in this PR?

**Comment by edewata** [comment]
@ckelleyRH Whoops.. they got added after I reordered the patches. Should be fixed now. Good catch! :)

**Review by ckelleyRH — APPROVED** [review]
Don't fully understand what's happening with the fixups to other files in addition to the `.gitignore`, but it already got approved in another branch so LGTM.

**Comment by edewata** [comment]
@ckelleyRH Thanks! Basically the other changes are just updating outdated files, removing obsolete tests, and some reorganizations so the CI can work again.

**Pull request merged**
