### PR TITLE
Add missing annotations to org.mozilla.jss.ssl.javax

### PR DESCRIPTION
**Pull request by ckelleyRH**
Resolves #705.

### CODE REVIEW

**Comment by ckelleyRH** [comment]
I thought this might happen, might have a case here of methods with the same name but different signatures. Needs another look.

**Comment by cipherboy** [comment]
@ckelleyRH 
> I thought this might happen, might have a case here of methods with the same name but different signatures. Needs another look.

Is this because of the failing JDK8 test? I didn't add `@Override` because the ones in the failing don't strictly override: depending on JDK versions, these features just haven't been backported (into older JDK versions) and thus aren't actually an override there.

You'd need conditional annotations based on versions... :)

**Comment by ckelleyRH** [comment]
I've updated that Java 8 workflow in #739 to use Java 11 so should pass this time.

**Review by edewata — APPROVED** [review]
LGTM

**Pull request merged**
