### PR TITLE
Make GitHub workflow use F34, drop EOL F32

### PR DESCRIPTION
**Pull request by ckelleyRH**

### CODE REVIEW

**Comment by ckelleyRH** [comment]
I created a `fedora_34` dockerfile, it's a carbon coby of the `fedora_33` dockerfile with `s/33/34`.

**Comment by edewata** [comment]
For `required.yml` there's still a problem with the `PKCS11Constant` test (see PR #689), so you might want to remove lines 32-41 for now, then I can rebase PR #689.

**Comment by ckelleyRH** [comment]
OK, thanks, I just found that PR - hadn't realised you'd already started on this, sorry!

**Review by edewata — APPROVED** [review]
No problem at all, this is good :)
So we isolate the problem, and continue to make progress everywhere else.

**Pull request merged**
