### PR TITLE
X509Certificate.getSubjectDN()and getIssuerDN() leak memory

### PR DESCRIPTION
**Pull request by uplogix-mmcclain**

### CODE REVIEW

**Review by cipherboy — APPROVED** [review]
I'd imagine there's lots of these cases lying around JSS... Wonder if it makes sense to create a macro for the `NewStringAndFree` pattern?

**Comment by uplogix-mmcclain** [comment]
Should I have called PORT_Free instead of free?

**Comment by cipherboy** [comment]
[Functionally they're equivalent...](https://github.com/nss-dev/nss/blob/master/lib/util/secport.c#L169-L175); you'd only redefine `PORT_free` if you wanted a different allocator for portability. It doesn't really matter too much IMO, but I'd perhaps prefer it for tradition if nothing else.

**Comment by fmarco76** [comment]
Hi @uplogix-mmcclain, this PR could be merged. Could you re-base the code. Thanks!

**Comment by uplogix-mmcclain** [comment]
Hi @fmarco76.  It looks like git did what I intended.  It should cleanly merge now.

**Comment by fmarco76** [comment]
Yes, sometime git is incredible!

**Pull request merged**
