### PR TITLE
Tidyup SSLClient and SSLServer

### PR DESCRIPTION
**Pull request by fmarco76**
Clean some of the SonarCloud complaints on SSLClient and SSLServer classes.

### CODE REVIEW

**Review by ckelleyRH — APPROVED** [review]
LGTM!

**Review by edewata — APPROVED** [review]
LGTM.

SonarCloud complains about Cognitive Complexity. It might be useful for new code, but we have a lot of complex legacy code. Should we just disable this warning? Regardless, feel free to merge.

**Comment by ckelleyRH** [comment]
> LGTM.
> 
> SonarCloud complains about Cognitive Complexity. It might be useful for new code, but we have a lot of complex legacy code. Should we just disable this warning? Regardless, feel free to merge.

I think it's a good idea, there are probably a lot of demons hiding in these very long, old methods.

**Comment by fmarco76** [comment]
I think it is good to remove the checks if you think the warning is not true. There are many cases where this happen and I will disable(e.g. we have warning asking to use try with resources in factory methods where the resources is the return value)

In this specific  case it is a good suggestion to simplify the method so we can leave in case we should change the method in the future.

**Comment by fmarco76** [comment]
Thanks @ckelleyRH and @edewata

**Pull request merged**
