### PR TITLE
Sync JSS with NSS's TLS cipher suite lists

### PR DESCRIPTION
**Pull request by cipherboy**
This includes a few new TLS 1.3 ciphers, TLS names for old SSL ciphers,
and RFC5487 support.

I'd like review on a few points:

1. I'm not sure if the omission of `TLS_NULL_WITH_NULL_NULL` was intentional or not, but I've gone ahead and added it.
2. There are several new TLS-for-SSL names--should I deprecate the SSL names? E.g., JSS already has `SSL3_RSA_EXPORT_WITH_RC4_40_MD5` but I've added `TLS_RSA_EXPORT_WITH_RC4_40_MD5`.
3. The introduction of `TLS_EMPTY_RENEGOTIATION_INFO_SCSV` and `TLS_FALLBACK_SCSV` -- I'm not sure if they were intentionally missing.
4. Adding them to the test suite.

`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`

### CODE REVIEW

**Comment by edewata** [comment]
@jmagne, could you take a look at this? Thanks.

I don't have any objection about this patch.

**Comment by edewata** [comment]
Just a note, we eventually want to replace the cipher constants in SSLSocket and the ciphers in jssCipherSuites with SSLCipher.

**Comment by emaldona** [comment]
From a conversation @cipherboy and @emaldona had on IRC
<emaldonado> cipherboy: https://security.stackexchange.com/questions/135998/ssl-tls-ciphersuite-tls-null-with-null-null
<emaldonado> don't know if it should be marked as deprecated, let me look at NSS code
<emaldonado> also https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.gska100/csdcwh.htm
<emaldonado> they only list them, don't make any recommendations
<cipherboy> Yeah, I'm kinda of the mind that JSS should be an unopinionated wrapper over NSS on things like constants.
<cipherboy> If NSS includes it, then JSS might as well.
<emaldonado> https://dxr.mozilla.org/mozilla-central/source/security/nss/lib/ssl/sslproto.h
<emaldonado> I see in the code
<emaldonado> emaldonado@localhost lib]$ grep -r NULL_WITH_NULL .
<emaldonado> ./ssl/ssl3con.c:      { TLS_NULL_WITH_NULL_NULL, cipher_null, ssl_mac_null, kea_null, ssl_hash_none },
<emaldonado> ./ssl/sslproto.h:#define SSL_NULL_WITH_NULL_NULL                TLS_NULL_WITH_NULL_NULL
<emaldonado> ./ssl/sslproto.h:#define TLS_NULL_WITH_NULL_NULL                 0x0000
<cipherboy> Yeah, it is definitely there, and will be needed to support TLS1.1 and perhaps 1.2...
<cipherboy> ...but until TLS 1.9 comes out and _everyone_ has dropped support for TLS 1.1 and TLS1.2 (and perhaps 1.3), I doubt NSS will remove it. :-)
<emaldonado> [emaldonado@localhost ssl]$ /usr/lib64/nss/unsupported-tools/listsuites | grep WITH_NULL
<emaldonado> TLS_ECDHE_ECDSA_WITH_NULL_SHA:
<emaldonado> TLS_ECDHE_RSA_WITH_NULL_SHA:
<emaldonado> TLS_ECDH_RSA_WITH_NULL_SHA:
<emaldonado> TLS_ECDH_ECDSA_WITH_NULL_SHA:
<emaldonado> TLS_RSA_WITH_NULL_SHA:
<emaldonado> TLS_RSA_WITH_NULL_SHA256:
<emaldonado> TLS_RSA_WITH_NULL_MD5:
<emaldonado> that tool doesn't list it and tests don't make reference to it, The ssltap tool does use it
<emaldonado> TLS_EMPTY_RENEGOTIATION_INFO_SCSV is mentioned in unit tests
<emaldonado> https://dxr.mozilla.org/mozilla-central/source/security/nss/gtests/ssl_gtest/ssl_v2_client_hello_unittest.cc
<emaldonado> the same with TLS_FALLBACK_SCSV
<emaldonado> cmd/tstclnt/tstclnt.c: uses it

So I think they should be added and I agree with @cipherboy on 
"JSS should be an unopinionated wrapper over NSS on things like constants."

**Comment by jmagne** [comment]
This looks reasonable to me. Making things closer to nss. I also like the adding of new versions of constants already present. For now we can just leave the old ones.

**Comment by cipherboy** [comment]
Thanks all for the reviews! Merging...

**Pull request merged**
